Refactor commit_message to allow custom prompts
rtwfroody/gpt-commit-msg pull request #1
Opened 2023-05-12 12:54 UTC by Jasha10

Hello,

Thank you for open sourcing this project!

This PR allows the user to pass a custom `--prompt` via the command line.

2023-05-12 17:09 UTC, rtwfroody requested changes
Thanks for sharing this. Looks like a nice improvement.

2023-05-12 17:09 UTC, rtwfroody commented on gpt_commit_msg.py
> +
Instead of doing this, can you pass the default prompt using `default=` as a parameter to `--prompt` argument?

2023-05-15 08:51 UTC, Jasha10 commented on gpt_commit_msg.py
> +
Sure, I've updated the code in commit https://github.com/rtwfroody/gpt-commit-msg/pull/1/commits/79938e38d8532051bc4be6ee4dc646ed0f4cb67e.
Thanks for the feedback!

2023-05-15 08:54 UTC, Jasha10 commented
FYI The newline characters and spaces in the prompt are tokenized and sent to GPT:
```python
                        default="""Write a git commit message for the following. The message
                                starts with a one-line summary of 60 characters, followed by a
                                blank line, followed by a longer but concise description of the
                                change."""
```
This default prompt has a newline character and a bunch of spaces at the beginning of each line. If this is of concern to you @rtwfroody, I can submit another PR to fix it.

2023-05-16 00:33 UTC, rtwfroody approved these changes
Thank you!

2023-05-16 00:34 UTC, merged

2023-05-16 00:34 UTC, rtwfroody commented
Good point about the tokens. I kind of assumed that any amount of whitespace is just a single token, but it sounds like that's not the case. That would be a nice thing to fix as well.

2023-05-17 02:31 UTC, Jasha10 commented
> I kind of assumed that any amount of whitespace is just a single token

Using the [openai/tiktoken](https://github.com/openai/tiktoken) library (which is a dependency of `gpt-commit-msg` I've been able to confirm that different amounts of whitespace result in different tokens, and newlines are treated differently from spaces.

I'll follow up with another PR.